name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: swift --version
      - run: swift build
      - run: swift test
